databases:
  - name: formulario-db
    plan: free
    databaseName: formulario_db
    user: formulario_user

services:
  - type: web
    name: fromulario-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: formulario-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: formulario-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: formulario-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: formulario-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: formulario-db
          property: password
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
