databases:
  - name: formulario-db
    plan: free
    databaseName: formulario_db
    user: formulario_user

services:
  - type: web
    name: fromulario-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: formulario-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: formulario-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: formulario-db
          property: password
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
